name: Deploy to VPS

on:
  push:
    branches: [ "main","master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            if [ ! -d "${{ secrets.VPS_PATH }}" ]; then
              mkdir -p "${{ secrets.VPS_PATH }}"
              git clone ${{ github.server_url }}/${{ github.repository }} "${{ secrets.VPS_PATH }}"
            fi
            cd "${{ secrets.VPS_PATH }}"
            git fetch --all
            # détecte la branche par défaut (main/master/...)
            DEFAULT_BRANCH="$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@')"
            echo "Default branch is: ${DEFAULT_BRANCH}"

            git reset --hard "origin/${DEFAULT_BRANCH}"

            docker compose up -d --build
            docker compose ps